name: piscina_app
description: 'PoolTest Pro'

version: 1.0.0+7


environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  fl_chart: ^0.63.0
  intl: ^0.19.0
  provider: ^6.0.0
  add_2_calendar: ^3.0.1
  timezone: ^0.9.2
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  uses-strings: true


flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#B3E5FC"
  image: assets/images/logo.png
  ios_content_mode: center
  android_gravity: center
  android: true
  ios: true

